// Generated by scripts/generate-icons.mjs (npm run icons). Don't edit by hand.

export const BRAND_MARK = {
  // The whole 512 × 512 icon canvas, and a box cropped close around the mark.
  canvas: '0 0 512 512',
  cropped: '128 96 254 319',
  cornerRadius: 110,
  top: 'M128 96 H250 A92 92 0 0 1 339.84 207.8 L128 274 Z',
  bottom: 'M128 324 L351.15 254.27 A92 92 0 0 1 290 415 H128 Z',
  colors: { background: '#9FE870', top: '#347821', bottom: '#163300' }
} as const;
